### PR TITLE
New force-alignment API and two-pass alignment to get phone/state durations

### PR DESCRIPTION
**Pull request by dhdaines**
Now you can (relatively) easily do a second pass of alignment to get phone durations after decoding or word alignment.

Also, word alignment now uses FSG search, like SoundSwallower, so it's really fast and also handles silence and alternate pronunciations for you.

### CODE REVIEW

**Comment by lenzo-ka** [comment]
Excited to check this out! I'm at Interspeech and out of phase by half day and all, but I'll get a look shortly

**Comment by dhdaines** [comment]
No problem! The CLI for state alignment isn't quite there yet, but coming soon (tonight, I hope).

**Comment by jsalsman** [comment]
Fantastic! I also hope to try this out ASAP. I wonder whether constraining
to the first pass's word boundaries will help. It seems like it can't hurt,
but it would be interesting to measure how much.

**Comment by dhdaines** [comment]
> Fantastic! I also hope to try this out ASAP. I wonder whether constraining to the first pass's word boundaries will help. It seems like it can't hurt, but it would be interesting to measure how much.

It will definitely make the alignment *faster*.  It may make it more accurate though I am not certain of this - I have to look at how I implemented this back in 2006: https://www.cs.cmu.edu/~dhuggins/Publications/phlab.pdf

**Review by lenzo-ka — APPROVED** [review]
Hoping for state level alignments, and frame level scores also, but LGTM and WFM

**Comment by dhdaines** [comment]
> Hoping for state level alignments, and frame level scores also, but LGTM and WFM

State level alignments are already there in the Python API, look at cython/test/alignment_test.py for an example, but it is now easy to add them to the command-line front-end as well, so I'll do that (not on by default though)

**Pull request merged**
