### PR TITLE
Fix _pocketsphinx.pyx's set_alignment example

### PR DESCRIPTION
**Pull request by jsalsman**
make the pocketsphinx.Decoder.set_alignment example print something legible

### CODE REVIEW

**Comment by jsalsman** [comment]
Hi @dhdaines! I'm working through the top item on slide 5 of https://bit.ly/talknicerslides and am really digging the sub-word alignment interface in Python. I wish I had known how to do this with the C API.

**Comment by dhdaines** [comment]
Ah oops! Thanks for fixing that docstring, as you noticed, those are AlignmentEntry objects and not strings.

**Comment by jsalsman** [comment]
@dhdaines this does not seem to have made it to https://pocketsphinx.readthedocs.io/en/latest/pocketsphinx.html#pocketsphinx.Decoder.set_alignment yet?
Screenshot 2024-09-08 7 47 35 AM

**Comment by dhdaines** [comment]
Oh... thanks for pointing this out.  There's a problem in the RTD build: https://readthedocs.org/projects/pocketsphinx/builds/25218590/

I'll fix it shortly.

**Comment by jsalsman** [comment]
@dhdaines happy to help. Please comment on https://github.com/cmusphinx/cmudict/issues/37

**Pull request merged**
